version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: on-failure

  app:
    container_name: key_value_manager
    build:
      context: ./
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mongo

volumes:
  mongo-data:
